function Hd = FilterW1_W2Hz(Fpass1,Fpass2)
 % All frequency values are in Hz.
 % Fs = Sampling Frequency
 % Fpass1 = First Passband Frequency
 % Fpass2 = Second Passband Frequency
%FILTERW1_1W2HZ Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.11 and the Signal Processing Toolbox 6.14.
%
% Generated on: 19-Aug-2015 18:40:04
%

% Equiripple Bandpass filter designed using the FIRPM function.
Fs = 1000;
Fstop1 = Fpass1;                % First Stopband Frequency
Fstop2 = Fpass2+0.5;                % Second Stopband Frequency
Dstop1 = 0.001;  % First Stopband Attenuation
Dpass  = 0.1;    % Passband Ripple
Dstop2 = 0.001;  % Second Stopband Attenuation
dens   = 20;     % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 (Fpass1 + .5) Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]

end
